# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fullstack-admin"
  s.version = "0.2.23"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mcasimir"]
  s.date = "2013-01-29"
  s.description = "Administration interface framework for fullstack"
  s.email = "maurizio.cas@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".project",
    "CHANGES.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "TODO.tasks",
    "VERSION",
    "app/assets/images/drag-handle.png",
    "app/assets/images/iconic/gray/calendar_12x12.png",
    "app/assets/images/iconic/gray/magnifying_glass_12x12.png",
    "app/assets/images/iconic/gray/x_11x11.png",
    "app/assets/images/loading.gif",
    "app/assets/images/smoothness/ui-bg_flat_0_aaaaaa_40x100.png",
    "app/assets/images/smoothness/ui-bg_flat_75_ffffff_40x100.png",
    "app/assets/images/smoothness/ui-bg_glass_55_fbf9ee_1x400.png",
    "app/assets/images/smoothness/ui-bg_glass_65_ffffff_1x400.png",
    "app/assets/images/smoothness/ui-bg_glass_75_dadada_1x400.png",
    "app/assets/images/smoothness/ui-bg_glass_75_e6e6e6_1x400.png",
    "app/assets/images/smoothness/ui-bg_glass_95_fef1ec_1x400.png",
    "app/assets/images/smoothness/ui-bg_highlight-soft_75_cccccc_1x100.png",
    "app/assets/images/smoothness/ui-icons_222222_256x240.png",
    "app/assets/images/smoothness/ui-icons_2e83ff_256x240.png",
    "app/assets/images/smoothness/ui-icons_454545_256x240.png",
    "app/assets/images/smoothness/ui-icons_888888_256x240.png",
    "app/assets/images/smoothness/ui-icons_cd0a0a_256x240.png",
    "app/assets/javascripts/fullstack/admin.js.coffee",
    "app/assets/javascripts/fullstack/admin/lib/ajax-chosen.js",
    "app/assets/javascripts/fullstack/admin/lib/bootstrap.min.js",
    "app/assets/javascripts/fullstack/admin/lib/combobox.js",
    "app/assets/javascripts/fullstack/admin/lib/jquery.noty.js",
    "app/assets/javascripts/fullstack/admin/lib/jquery.tagsinput.js",
    "app/assets/javascripts/fullstack/admin/lib/jquery.ui.datepicker-it.js",
    "app/assets/javascripts/fullstack/admin/lib/jquery.validate.it.js",
    "app/assets/javascripts/fullstack/admin/lib/jquery.validate.js",
    "app/assets/javascripts/fullstack/admin/lib/notify.js.coffee",
    "app/assets/javascripts/fullstack/admin/lib/slider_input.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/ajax_loading.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/bootstrap.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/facebox.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/file_input.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/forms.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/index_delete_button.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/nested_forms.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/prevent_submit_on_enter.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/sortable.js.coffee",
    "app/assets/javascripts/fullstack/admin/src/uploads.js.coffee",
    "app/assets/javascripts/jquery-migrate-to-1.9.js",
    "app/assets/stylesheets/fullstack/admin.css",
    "app/assets/stylesheets/fullstack/admin/lib/bootstrap-overrides.css",
    "app/assets/stylesheets/fullstack/admin/lib/bootstrap.min.css",
    "app/assets/stylesheets/fullstack/admin/lib/jquery-ui.css",
    "app/assets/stylesheets/fullstack/admin/lib/jquery.noty.css",
    "app/assets/stylesheets/fullstack/admin/lib/jquery.tagsinput.css",
    "app/assets/stylesheets/fullstack/admin/src/ajax-loading.css",
    "app/assets/stylesheets/fullstack/admin/src/dialog.css",
    "app/assets/stylesheets/fullstack/admin/src/facebox.css",
    "app/assets/stylesheets/fullstack/admin/src/forms.css",
    "app/assets/stylesheets/fullstack/admin/src/globals.css",
    "app/assets/stylesheets/fullstack/admin/src/helpers.css",
    "app/assets/stylesheets/fullstack/admin/src/jquery-ui.css",
    "app/assets/stylesheets/fullstack/admin/src/login.css",
    "app/assets/stylesheets/fullstack/admin/src/notify.css",
    "app/assets/stylesheets/fullstack/admin/src/plupload.css",
    "app/controllers/admin/base_controller.rb",
    "app/controllers/admin/positionables_controller.rb",
    "app/controllers/admin/responder.rb",
    "app/controllers/admin/scaffold_controller.rb",
    "app/controllers/admin/sessions_controller.rb",
    "app/controllers/admin/subject_model_adapter.rb",
    "app/helpers/admin_form_helper.rb",
    "app/helpers/scaffold_helper.rb",
    "app/inputs/country_input.rb",
    "app/inputs/daterange_input.rb",
    "app/inputs/datetime_input.rb",
    "app/inputs/datetime_select_input.rb",
    "app/inputs/file_input.rb",
    "app/inputs/iso3166.rb",
    "app/inputs/string_input.rb",
    "app/inputs/tag_list_input.rb",
    "app/inputs/taglist_input.rb",
    "app/inputs/tags_input.rb",
    "app/inputs/text_input.rb",
    "app/models/administrator.rb",
    "app/models/authenticatable.rb",
    "app/models/confirmable.rb",
    "app/models/positionable.rb",
    "app/models/recoverable.rb",
    "app/models/registerable.rb",
    "app/models/rememberable.rb",
    "app/models/roleable.rb",
    "app/models/suspendable.rb",
    "app/models/trackable.rb",
    "app/views/admin/_nav.html.erb",
    "app/views/admin/base/_associated_resources_table.html.erb",
    "app/views/admin/base/_form.html.erb",
    "app/views/admin/base/_index.html.erb",
    "app/views/admin/base/_nested_belongs_to_fields.html.erb",
    "app/views/admin/base/_nested_form.html.erb",
    "app/views/admin/base/_sort.html.erb",
    "app/views/admin/base/destroy.js.coffee",
    "app/views/admin/base/edit.html.erb",
    "app/views/admin/base/index.html.erb",
    "app/views/admin/base/new.html.erb",
    "app/views/admin/base/update.js.coffee",
    "app/views/admin/positionables/_collection.html.erb",
    "app/views/admin/sessions/new.html.erb",
    "app/views/kaminari/_first_page.html.erb",
    "app/views/kaminari/_gap.html.erb",
    "app/views/kaminari/_last_page.html.erb",
    "app/views/kaminari/_next_page.html.erb",
    "app/views/kaminari/_page.html.erb",
    "app/views/kaminari/_paginator.html.erb",
    "app/views/kaminari/_prev_page.html.erb",
    "app/views/layouts/admin.html.erb",
    "app/views/layouts/admin/dialog.html.erb",
    "app/views/layouts/login.html.erb",
    "config/initializers/ckeditor_setup.rb",
    "config/initializers/formtastic_bootstrap_timeish_hack.rb",
    "config/locales/devise.en.yml",
    "config/locales/devise.views.en.yml",
    "config/locales/devise.views.it.yml",
    "config/locales/en.yml",
    "config/locales/groups.it.yml",
    "config/locales/iso3166.da.yml",
    "config/locales/iso3166.en.yml",
    "config/locales/iso3166.es.yml",
    "config/locales/iso3166.fr.yml",
    "config/locales/iso3166.it.yml",
    "config/locales/iso3166.ru.yml",
    "config/locales/it.yml",
    "config/locales/kaminari.en.yml",
    "config/locales/kaminari.it.yml",
    "config/locales/labels.it.yml",
    "config/locales/locale_names.en.yml",
    "config/locales/locale_names.it.yml",
    "config/locales/resources.it.yml",
    "config/routes.rb",
    "fullstack-admin.gemspec",
    "lib/fullstack-admin.rb",
    "lib/fullstack/admin.rb",
    "lib/fullstack/admin/engine.rb",
    "lib/fullstack/admin/resources.rb",
    "lib/generators/fullstack/admin/install_generator.rb",
    "lib/generators/fullstack/admin/locale_generator.rb",
    "lib/generators/fullstack/admin/scaffold_generator.rb",
    "lib/generators/fullstack/admin/templates/root/app/assets/javascripts/admin/admin.js.coffee",
    "lib/generators/fullstack/admin/templates/root/app/assets/stylesheets/admin/admin.css",
    "lib/generators/fullstack/admin/templates/root/app/controllers/admin/dashboard_controller.rb",
    "lib/generators/fullstack/admin/templates/root/app/models/user.rb",
    "lib/generators/fullstack/admin/templates/root/app/views/admin/dashboard/show.html.erb",
    "lib/generators/fullstack/admin/templates/root/lib/support/user_subject.rb",
    "lib/generators/fullstack/admin/templates/root/public/img/glyphicons-halflings-white.png",
    "lib/generators/fullstack/admin/templates/root/public/img/glyphicons-halflings.png",
    "lib/generators/fullstack/admin/templates/scaffold/_filter.html.erb",
    "lib/generators/fullstack/admin/templates/scaffold/controller.rb",
    "lib/generators/fullstack/admin/templates/scaffold/views/_form.html.erb.tt",
    "lib/generators/fullstack/admin/templates/scaffold/views/_index.html.erb.tt"
  ]
  s.homepage = "http://github.com/mcasimir/kaminari-bootstrap"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Administration interface framework for fullstack"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2"])
      s.add_runtime_dependency(%q<fullstack>, ["~> 0.1.27"])
      s.add_runtime_dependency(%q<bootstrap-helpers>, ["~> 0.1.9"])
      s.add_runtime_dependency(%q<chosen-rails>, [">= 0"])
      s.add_runtime_dependency(%q<fullstack-ckeditor>, ["~> 0.1.3"])
      s.add_runtime_dependency(%q<facebox-rails>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic-bootstrap>, [">= 0"])
      s.add_runtime_dependency(%q<meta_search>, [">= 0"])
      s.add_runtime_dependency(%q<plupload-rails>, [">= 0"])
      s.add_runtime_dependency(%q<has-attached>, ["~> 0.2.5"])
      s.add_runtime_dependency(%q<bootstrap-datepicker-rails>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2"])
      s.add_dependency(%q<fullstack>, ["~> 0.1.27"])
      s.add_dependency(%q<bootstrap-helpers>, ["~> 0.1.9"])
      s.add_dependency(%q<chosen-rails>, [">= 0"])
      s.add_dependency(%q<fullstack-ckeditor>, ["~> 0.1.3"])
      s.add_dependency(%q<facebox-rails>, [">= 0"])
      s.add_dependency(%q<formtastic-bootstrap>, [">= 0"])
      s.add_dependency(%q<meta_search>, [">= 0"])
      s.add_dependency(%q<plupload-rails>, [">= 0"])
      s.add_dependency(%q<has-attached>, ["~> 0.2.5"])
      s.add_dependency(%q<bootstrap-datepicker-rails>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2"])
    s.add_dependency(%q<fullstack>, ["~> 0.1.27"])
    s.add_dependency(%q<bootstrap-helpers>, ["~> 0.1.9"])
    s.add_dependency(%q<chosen-rails>, [">= 0"])
    s.add_dependency(%q<fullstack-ckeditor>, ["~> 0.1.3"])
    s.add_dependency(%q<facebox-rails>, [">= 0"])
    s.add_dependency(%q<formtastic-bootstrap>, [">= 0"])
    s.add_dependency(%q<meta_search>, [">= 0"])
    s.add_dependency(%q<plupload-rails>, [">= 0"])
    s.add_dependency(%q<has-attached>, ["~> 0.2.5"])
    s.add_dependency(%q<bootstrap-datepicker-rails>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

